services:
  gateway-rf:
    image: jeserna/gateway-rf:v0.0.38
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway-rf.entrypoints=web"
      - "traefik.http.routers.gateway-rf.rule=PathPrefix(`/api/`)"
      - "traefik.http.services.gateway-rf.loadbalancer.server.port=8080"
    container_name: gateway-rf
    env_file:
      - ${SECRETS_DIR:-/opt/secrets}/common-configs.env

    restart: unless-stopped
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health/liveness"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
      start_interval: 10s
networks:
  dokploy-network:
    external: true
